version: "2"

services:
    app:
        build: images/app
        depends_on:
            - selenium
            - api
        ports:
            - "8101:8101"
        networks:
            - my-net
        working_dir: /app
        volumes:
            - ../dtl-app:/app
        command: bash -c "npm install && node_modules/bower/bin/bower install --allow-root && cd ./www && python -m SimpleHTTPServer 8101"

    api:
        build: images/api
        depends_on:
            - mysql
        ports:
            - "3030:3030"
        networks:
            - my-net
        working_dir: /app
        volumes:
            - ../dtl-api:/app
        depends_on:
            - mysql
        environment:
            - NODE_ENV=development
            - MYSQL_PORT=3306
            - MYSQL_USERNAME=root
            - MYSQL_PASSWORD=verysecret
        command: bash -c "npm install && node_modules/bower/bin/bower install --allow-root && npm run start-dev"

    mysql:
       build: images/mysql
       ports:
           - "3306:3306"
       volumes_from:
           - mysql-data
       networks:
           - my-net
       environment:
           - USERNAME=root
           - PASSWORD=verysecret
           - MYSQL_ROOT_PASSWORD=verysecret

    mysql-data:
        build: images/mysql/mysql-data
        volumes:
            - mysqlvolume:/var/lib/mysql
        command: /bin/true

    selenium:
        build: images/selenium
        container_name: selenium
        ports:
            - "4444:4444"
        networks:
            - my-net

networks:
    my-net:
        driver: bridge

volumes:
    mysqlvolume:
        driver: local

